# Generated by Django 4.2 on 2024-09-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_record_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Диагноз'),
        ),
    ]
